algo = input('Digite algo: ')
print('O tipo primitivo desse valor é {}.'.format(type(algo)))
print('Só tem espaços? {}'.format(algo.isspace()))
print('É alfabético? {}'.format(algo.isalpha()))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfanumérico? {}'.format(algo.isalnum()))
print('Está todo em MAÍSCULAS? {}'.format(algo.isupper()))
print('Está todo em minúsculas? {}'.format(algo.islower()))
print('Está Capitalizado? '.format(algo.istitle()))
